CREATE DATABASE IF NOT EXISTS auth;
USE auth;

CREATE OR REPLACE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(128) NOT NULL UNIQUE,
  password_hash VARCHAR(256) NOT NULL,
  name VARCHAR(128),
  surname VARCHAR(128)
);

