CREATE DATABASE IF NOT EXISTS ecommerce;

USE ecommerce;

DROP TABLE IF EXISTS products_orders;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products_carts;
DROP TABLE IF EXISTS carts;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL,
  surname VARCHAR(64) NOT NULL
);

CREATE TABLE products (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL,
  description TEXT,
  image_url VARCHAR(512),
  price FLOAT NOT NULL
);

CREATE TABLE carts (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products_carts (
  product_id INT NOT NULL REFERENCES products(id),
  cart_id INT NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
  quantity INT NOT NULL,
  PRIMARY KEY (product_id, cart_id)
);

CREATE TABLE orders (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products_orders (
  product_id INT NOT NULL REFERENCES products(id),
  order_id INT NOT NULL REFERENCES orders(id),
  quantity INT NOT NULL,
  price FLOAT NOT NULL,
  PRIMARY KEY (product_id, order_id)
);

